export const genreOptions = [
  { value: "133", label: "Comedy" },
  { value: "99", label: "News" },
  { value: "77", label: "Sports" },
  { value: "127", label: "Technology" },
  { value: "93", label: "Business" },
  { value: "134", label: "Music" },
  { value: "125", label: "History" },
  { value: "151", label: "Locally Focused" },
  { value: "132", label: "Kids & Family" },
  { value: "168", label: "Fiction" },
  { value: "122", label: "Society & Culture" },
  { value: "88", label: "Health & Fitness" },
  { value: "100", label: "Arts" },
  { value: "69", label: "Religion & Spirituality" },
  { value: "117", label: "Government" },
  { value: "135", label: "True Crime" },
  { value: "68", label: "TV & Film" },
  { value: "78", label: "Science" },
  { value: "98", label: "Technology" },
  { value: "122", label: "Philosophy" },
  { value: "99", label: "Politics" },
  { value: "79", label: "History" },
  { value: "128", label: "Education" },
  { value: "100", label: "Literature" },
  { value: "130", label: "Self-Help" },
  { value: "80", label: "Music" },
  { value: "102", label: "Video Games" },
  { value: "82", label: "Food" },
  { value: "110", label: "Hobbies" },
  { value: "84", label: "Fashion & Beauty" },
  { value: "85", label: "Travel" },
  { value: "89", label: "Business" },
  { value: "87", label: "Investing" },
  { value: "123", label: "Science" },
  { value: "104", label: "Medicine" },
  { value: "105", label: "Fitness" },
  { value: "106", label: "Nutrition" },
  { value: "107", label: "Mental Health" },
  { value: "108", label: "Relationships" },
  { value: "109", label: "Parenting" },
  { value: "111", label: "Education" },
  { value: "112", label: "Language Learning" },
  { value: "113", label: "Technology" },
  { value: "114", label: "Software Development" },
  { value: "116", label: "Design" },
  { value: "118", label: "Marketing" },
  { value: "120", label: "Entrepreneurship" },
  { value: "121", label: "Management" },
  { value: "123", label: "Philosophy" },
  { value: "124", label: "Religion" },
  { value: "126", label: "Society" },
  { value: "129", label: "Culture" },
  { value: "131", label: "Psychology" },
  { value: "133", label: "Biography" },
  { value: "136", label: "True Crime" },
  { value: "137", label: "Film Reviews" },
  { value: "138", label: "TV Reviews" },
  { value: "139", label: "Books" },
  { value: "140", label: "Sports" },
  { value: "141", label: "Football" },
  { value: "142", label: "Basketball" },
  { value: "143", label: "Baseball" },
  { value: "144", label: "Soccer" },
  { value: "145", label: "Tennis" },
  { value: "146", label: "Golf" },
  { value: "147", label: "Hockey" },
  { value: "148", label: "Martial Arts" },
  { value: "149", label: "Boxing" },
  { value: "150", label: "Wrestling" },
  { value: "151", label: "Cricket" },
  { value: "152", label: "Rugby" },
  { value: "153", label: "Motorsports" },
  { value: "154", label: "Fitness" },
  { value: "155", label: "Running" },
];
